server:
  port: 3002
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:3000/eureka
  instance:
    preferIpAddress: true
spring:
  application:
    name: single-customer
  zipkin:
    base-url: http://localhost:9411/ # zipkin查询服务器实例的URL
    sender:
      type: web # 将span发送到Zipkin的方法。
  sleuth:
    sampler:
      probability: 1 # 设置sleuth收集信息的比率，默认0.1，最大是1，数字越大越耗性能