server:
  port: 3001
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
spring:
  application:
    name: single-provider
  zipkin:
    base-url: http://localhost:9411/
    #sleuth的数据显示在zipkin
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1 # 配置采样百分比,开发环境可以设置为1,表示全部,生产环境用默认